---

container_fail:
  error_at_launch: false

container:
  - name: busybox
    hostname: busybox
    image: busybox:1.35.0

container_post_tasks:
  - /usr/local/bin/remove_untagged_images.sh
  - /usr/local/bin/list_all_images.sh

...
