---

- name: created application directories  # noqa no-handler
  ansible.builtin.debug:
    msg: "{{ _created_directories.created_directories }}"
  when:
    - _created_directories.changed
    - _created_directories.created_directories is defined

- name: created container volumes and mountpoints  # noqa no-handler
  ansible.builtin.debug:
    msg: "{{ _created_directories.created_directories }}"
  when:
    - _created_directories.changed
    - _created_directories.created_directories is defined

- name: update container for recreate running docker instance
  ansible.builtin.set_fact:
    container: "{{ _container_data.container_data }}"
  when:
    - _container_data is defined
    - _container_data.container_data is defined

- name: created environnments or properties  # noqa no-handler
  ansible.builtin.debug:
    msg: "{{ _container_data.msg }}"
  when:
    - _container_data is defined
    - _container_data.msg is defined
    - _container_data.changed

...
